### ISSUE TITLE
Version 1.7.0 fails on Krypton over inputstream.adaptive 2.0.19

### ISSUE THREAD

**Issue by dagwieers** [pietje666/plugin.video.vrt.nu#109]
**Describe the bug**
Last night I was not able to install the VRT.NU addon version 1.7.0 on a Kodi Krypton (17.6) because of the inputstream.adaptive requirement.

I think we need to release v1.7.1 with this dependency removed (or marked as optional ?).

**Comment by dagwieers** [comment]
@mediaminister This was introduced with https://github.com/pietje666/plugin.video.vrt.nu/commit/27cd3e5de0d0eef703343e5aa25f4c6995f36c86 and I have to confess I didn't understand this consequence for Krypton.

This was also reported before in: https://github.com/pietje666/plugin.video.vrt.nu/issues/48)

**Comment by dagwieers** [comment]
Based on the information from @pietje666 I did not want to wait any longer to get this fix out.
https://github.com/xbmc/repo-plugins/pull/2352

**Comment by mediaminister** [comment]
Kodi 17.6 works with a previous version: inputstream.adaptive 2.0.**18**
Maybe we don't have to remove this requirement completely. I'll investigate this later.

**Comment by pietje666** [comment]
It is recomended not to add dependencies on inputstream adaptive and let the inputstream helper handle it! (Kodi team told me)

**Comment by mediaminister** [comment]
But in fact inputstreamhelper isn't handling this currently. I'll see how to optimize this.

**Comment by dagwieers** [comment]
My first concern was to offer a working solutions to existing Krypton users.
But if we can improve this for the next release, that would be great.

**Comment by mediaminister** [comment]
I investigated this and made two pull requests to handle automatic installation of inputstream.adaptive in Kodi 18 when needed to play the mpeg_dash drm streams.
https://github.com/pietje666/plugin.video.vrt.nu/pull/112
https://github.com/emilsvennesson/script.module.inputstreamhelper/pull/53/files

In Kodi 17 inputstream.adaptive will never be installed because the streamservice class provides the hls streams and Kodi plays this format out of the box.
Limited support for non-drm mpeg_dash in Kodi 17 is possible with earlier versions of inputstream.adaptive but subtitling doesn't work. So, hls is the best choice.
If VRT would phase out support for hls or non-drm streams in the future, we can't support Kodi 17 any longer.

**Comment by dagwieers** [comment]
@mediaminister Would it help to require inputstream.adaptive 1.0.18 instead? Or is your fix for inputstreamhelper the solution ?

**Comment by mediaminister** [comment]
It's safer to let inputstreamhelper handle this.

**Comment by dagwieers** [comment]
Do I close this issue, or do we want to keep it for tracking something?

**Comment by mediaminister** [comment]
You can close this.
