### ISSUE TITLE
Same episodes show up in different seasons

### ISSUE THREAD

**Issue by dagwieers** [pietje666/plugin.video.vrt.nu#124]
### Describe the bug ###
I noticed this in the seasons of "Universiteit van Vlaanderen" which has 2 seasons listed: **Season 2018-2019** and **Season 2017-2018**. Both seasons have the same episodes listed.

For another Series "Thuis" this is not the case, although it does show episodes released every day for Season 21 and Season 24. (But I guess this is done by the VRT on purpose?)

**Comment by mediaminister** [comment]
For the series "Thuis, VRT broadcasts two episodes a day: one episode form an older season in the afternoon and one new episode in primetime. So, this is normal.

For "Universiteit van Vlaanderen", I fixed this problem by using the `doc_count` value from the seasons buckets as the size parameter and using `seasonName` instead of `seasonTitle` facet.
