### ISSUE TITLE
Raspberry Pi3 displays Overheating sign when the menu A-Z is standing open for a long time

### ISSUE THREAD

**Issue by pietje666** [pietje666/plugin.video.vrt.nu#17]
When i leave my Raspberry Pi3 on and the A-Z menu is opened then after a while i get the overheating sign. I have a Raspberry Pi3 without extra cooling or anything.

I have no idea why this is hapenning, i just use the standard Kodi ListItem infrastructure. 

I have this problem currently on Kodi 17.3 and before.

**Comment by JeanPoll** [comment]
I don't see this issue

**Comment by dagwieers** [comment]
I can confirm that Kodi (LibreELEC 8.2.5) is continuously using about 50% to 60% of one (out of 4 cores) when it's not doing anything in the A-Z menu (but not only in that menu, also other menus). Tracing that process's system calls it is continuously doing clock_gettime(), which I think is because of the main select()-loop in Kodi.

So I assume that this main loop is somehow processing more than it is doing usually. Maybe it's reprocessing every item in the list while that should not be needed, or something like that.

To compare, the main-loop (when not doing anything):
- only consumes about 12% on my main Kodi screen
- consumes about 11% in the movies listing
- consumes 12% in another addon's item listing

So somehow the baseline is around 11% and you probably cannot do any better than that. But now it's being 5x as high in our addon. We might get more information by using the kernel's perf utility.

**Comment by peno64** [comment]
Also working on a PI 3 with libreelec and I see some more CPU usage in that menu but not that much (15%) but I don't have the overheating sign. I do have a cooling on the cpu (no van) so I would suggest that you buy it for a couple of cents.

**Comment by dagwieers** [comment]
I do have an aluminium case with heatsinks for my RPi's, so I never had any temperature issues.
(And with the CPU usage I am seeing, at only 1/8 of the total capacity, I wouldn't expect any issues)

You can buy those cases for less than 8 EUR on AliExpress including shipping.

**Comment by pietje666** [comment]
not sure if this problem still applies so ill close it. (my flirc case never reaches max temp even when cpu is 100% for a long time)
