### ISSUE TITLE
Remove Stable and 1.10.1 branches

### ISSUE THREAD

**Issue by dagwieers** [pietje666/plugin.video.vrt.nu#354]
### Describe the feature ###
Shall we close the Stable and 1.10.1 branches ?

I don't mind creating a new stable branch when that need would arise, but what we have now is only confusing IMO.

**Comment by mediaminister** [comment]
I think Stable can be deleted completely, it's a very old branch that uses old web scraping functions that no longer work.
Just to be safe, I think we should wait to delete v1.10.1 branch because 2.0.0 is not yet available in the Kodi repo and the impact of 2.0.0 on some Kodi versions is still a blind spot.

P.S. I found a web page where we can follow the downloads of our add-on in detail: http://mirrors.kodi.tv/stats?downloadstats=2019-07&filter=plugin.video.vrt.nu

**Comment by dagwieers** [comment]
Ok. Nice page ! You can filter for totals by version like this:
http://mirrors.kodi.tv/stats?downloadstats&filter=plugin.video.vrt.nu-1.10.0
http://mirrors.kodi.tv/stats?downloadstats&filter=plugin.audio.vrt.radio

**Comment by dagwieers** [comment]
Stable branch has been removed after confirmation of @pietje666
