### ISSUE TITLE
Prepare for release v2.2.0

### ISSUE THREAD

**Issue by dagwieers** [pietje666/plugin.video.vrt.nu#426]
### Describe the feature ###
The upcoming v2.2.0 has accumulated quite few known issues, and new artwork.
From the open enhancements nothing seems very urgent either IMO.

Do we expect full closure for the remaining open bugs, or can we prepare for a new release shortly?

Feel free to add a list of things we should do/fix before releasing v2.2.0.

**Comment by dagwieers** [comment]
I would like to discuss what to do with the channel listings:
- Do we want to keep the fuzzy coloured studio icons as fanart?
- Do we want white channel icons as bullets, if this means we cannot use coloured thumbnails instead?

**Comment by dagwieers** [comment]
Also, I notices hundreds of these lines when running the unit tests:
```
Notice: [plugin.video.vrt.nu] Got cached token './test/userdata/XVRTToken.tkn'
Notice: [plugin.video.vrt.nu] Got cached token './test/userdata/XVRTToken.tkn'
Notice: [plugin.video.vrt.nu] Got cached token './test/userdata/XVRTToken.tkn'
Notice: [plugin.video.vrt.nu] Got cached token './test/userdata/XVRTToken.tkn'
Notice: [plugin.video.vrt.nu] Got cached token './test/userdata/XVRTToken.tkn'
Notice: [plugin.video.vrt.nu] Got cached token './test/userdata/XVRTToken.tkn'
Notice: [plugin.video.vrt.nu] Got cached token './test/userdata/XVRTToken.tkn'
Notice: [plugin.video.vrt.nu] Got cached token './test/userdata/XVRTToken.tkn'
```

**Comment by mediaminister** [comment]
> Do we expect full closure for the remaining open bugs, or can we prepare for a new release shortly?

I think we should release this week because the webscraper used by the TV guide is broken. I did a couple of tests already on Kodi python3 and Kodi 17 and it works fine. I'll do a couple of more tests in VMWare tonight and will report this as soon as possible.

> Do we want to keep the fuzzy coloured studio icons as fanart?

No, I don't like fuzzy.

> Do we want white channel icons as bullets, if this means we cannot use coloured thumbnails instead?

I like the white icons. I don't think you should change this for the 2.2.0 release.

> Also, I noticed hundreds of these lines when running the unit tests

I also noticed this since a couple of days and I don't remember seeing this before. I should investigate what's happening.

**Comment by dagwieers** [comment]
Ready for release. Countdown has started...
