### ISSUE TITLE
Use of colors can make the addon hard to use on lighter skins.

### ISSUE THREAD

**Issue by michaelarnauts** [pietje666/plugin.video.vrt.nu#508]
# Describe the bug ###
The use of colors to highlight some things should be avoided since light skins make these strings hard to read.

![image](https://user-images.githubusercontent.com/1193779/66141371-df783c00-e603-11e9-92ee-522e114b10de.png)

The color of the geoblocked and the "beschikbaar tot" is readable on my skin, but not so pretty. I can imagine it also being hard to see on other skins.

![image](https://user-images.githubusercontent.com/1193779/66141616-40a00f80-e604-11e9-989e-f5e92875b597.png)

**Comment by michaelarnauts** [comment]
Another place:

![image](https://user-images.githubusercontent.com/1193779/66141925-d9cf2600-e604-11e9-9145-b3a8dbe37d88.png)

**Comment by dagwieers** [comment]
Yeah, so there is no real solution to fix this, except not use colours at all. And then everybody loses because only a small set of users are using a light skin. (Light-coloured skins on TVs/projectors is fortunately not very common for obvious reasons).

The best solution would be that Kodi had support for:
- Theming / colouring (so that a highlighted colour is defined and we could use `[color highlight]`
- Supports typical VOD InfoLabels (like: availability, geo-blocked, etc.) so we don't need to add this to the plot (which is a hack in itself) and this information is put elsewhere (e.g. a lock-symbol for geo-locked content, or full unicode or even emoji support)
- Supports Live TV InfoLabels with support for EPG information

The only concession I am willing to make here is that we add to the settings either:
- the selection of a "highlight", "geo-blocked", "availability" colour, or
- a selection between "dark skin" or "light skin" (with a preset colouring by us)

**Comment by michaelarnauts** [comment]
* The selection of the current day could be done by simple making the full row bold.
* Geoblocked and availablitity is fine I guess.
* I also don't see the real benefit of highlighting the current program of the live channel in yellow. We could also try making this bold.

**Comment by dagwieers** [comment]
Geoblocked and availability is not fine, a blue or red background would render it unreadable as much as yellow on a white background. So if we plan to fix this, it should cover all possibilities.

And if we have to fix this by selecting colours, we might as well keep highlight in a custom "highlight" colour.

**Comment by dagwieers** [comment]
Another place where we emphasize text using colour is the highlighted keywords in search queries. We cannot make this bold because the original text could be in bold already, so we use yellow there too. So a "highlighted" colour would be the best solution here too.

**Comment by dagwieers** [comment]
I updated the [Kodi development](https://github.com/pietje666/plugin.video.vrt.nu/wiki/Kodi) page with shortcomings with more detailed information wrt. missing VOD/Live TV properties as well as the need to have a way for skins to expose colours for highlighting text. (Currently selected text is in green, I assume skins can already modify that colour as well)

**Comment by dagwieers** [comment]
The implement would add the following *three* new entries in the Interface settings
- **Colours**
  - Highlighted text colour: [yellow]
  - Availability text colour: [blue]
  - Geo-locked text colour: [red]

We could also make this more specific by adding:
  - Search keyword text colour: [yellow]

But I am not sure we need this level of customization as IMO the majority of users use the default (Estuary) skin. Additionally, instead of colours, we could also support bold or italic as options. (This would make it somewhat more complex to code, but would help for other output forms)

PS The implementation would also remove the colouring from the translation files, back into the code.

**Comment by dagwieers** [comment]
@michaelarnauts Can you verify our merged implementation with your skin again? I think we would like to release this the coming weeks.
