### ISSUE TITLE
Fout bij installeren/starten van VRT NU add-on

### ISSUE THREAD

**Issue by herwinc** [pietje666/plugin.video.vrt.nu#671]
### Describe the bug ###

raspberypi with LibreElec en Kodi. Update addon -> after download, I immediatly get an error. And the Addon does not start when clicked.

### To Reproduce ###
1. Go to ...Addons
2. Click on ....Updates
download
4. error

### Expected behavior ###

Addon starts when clicked after download, with new fantastic features

### Additional context ###

- Operating system: LibreElec 8.2.5 RPI2.arm
- Kodi version: 17.6
- Addon version: 2.3.0 (2.2.2 is ok)
- Using a VPN: no
- Country you are using the addon from: be

### Log (if available) ###
```log after download+error


```

**Comment by herwinc** [comment]
file:///tmp/_1033535.JPG

**Comment by herwinc** [comment]
![_1033535](https://user-images.githubusercontent.com/8471256/72187359-baac1580-33f7-11ea-8cbd-845ad270cb41.JPG)

**Comment by dagwieers** [comment]
Thanks for reporting. The issue is very clear. The configuration of the add-on has the **max_log_level** set to a string, and not an integer. This is how it used to be, but we changed this and implemented an automatic fix. Which does not seem to work for the service now.

The easiest workaround for now is that you open the VRT NU add-on settings, go to **Expert** settings and at the very bottom set **Log level** to **Info**. Then leave the settings by using **OK**. This should ensure the **max_log_level** becomes an integer.

This is definitely a bug that we need to fix asap and warrants a new release.

**Comment by dagwieers** [comment]
Ik denk dat we het hebben gefixed in de master branch. Als je deze versie zelf wil testen, dan kan dat via de volgende procedure: [Test the master branch](https://github.com/pietje666/plugin.video.vrt.nu/wiki/Testing#test-the-master-branch-or-any-other-branch)

**Comment by herwinc** [comment]
Thx. ik zal die log level = info doen.  btw, Daarnet nog eens geprobeerd via kodi repo 2.3.0: zelfde error na update. Daarna 'Cache: Clear VRT Tokens' gedaan en dan startte VRTNu wel. Is nu 2.3.0

**Comment by dagwieers** [comment]
Die Clear VRT Tokens is niet de oplossing geweest, gewoon naar de settings gaan en met OK verlaten is wellicht voldoende geweest.

**Comment by dagwieers** [comment]
We hebben een nieuwe versie v2.3.1 gereleased dat dit probleem oplost. Bedankt om het te melden!
